---
title: "Trabajo___1"
author: "Dana Carrasco"
format: html
editor: visual
bibliography: Trabajo1R.bib
link-citations: true
---

## Brechas de género: La conciliación de la doble presencia

El presente trabajo tiene por objetivo estudiar la brecha de género en torno a la distribución de las labores domésticas o trabajo reproductivo en el marco de la doble presencia que realizan las mujeres en Chile. Debido a la actual situación de presencialidad a la que se ven expuestas las mujeres al mismo tiempo en el trabajo reproductivo como en el trabajo remunerado. Como hipotesis de trabajo, tenemos que a medida que aumentan las horas de trabajo de la mujer, aumenta la ocupación del tiempo en labores domesticas del hombre. Además es relevante analizar cómo se divide el mercado laboral con la creciente participación de las mujeres en este, la cual en comparación con los hombres sigue siendo más baja según la CASEN (2022)  este fenómeno presenta  un aumento en la participación laboral de las mujeres, que pasó de 43,5% en 2006 a 52,0% en 2022, y a su vez la participación de los hombres se ha mantenido, si bien, con altos y bajos, en torno al 73% desde el inicio del período.

Sin embargo, esta división del mercado del trabajo trae consigo no tan solo pocas herramientas para enfrentarse al mercado laboral y a su vez a los cambios en el trabajo del hogar sino también en la ocupación del tiempo dentro del trabajo remunerado. Planteando así que "la teoría del mercado dual utiliza a la familia contra el empleo y se sustituye la tradicional división sexual del trabajo por una división sexual del tiempo de trabajo: el tiempo completo para los hombres, el tiempo parcial para las mujeres" (Icart, Santamaría, 2016) [ver @ignasibruneticart2016] . De esta forma, las mujeres dedicarían menos tiempo al trabajo remunerado y mayor tiempo a las labores domésticas. 

Existen ciertas actividades que están ligadas a la mujer socialmente. y que con ciertas particularidades se definen como trabajo reproductivo, este es  aquel que comprende acciones de cuidado y atención a la familia y el hogar. La singularidad que tiene el trabajo reproductivo es que este no es remunerado con un salario por lo que queda fuera del mercado laboral. Además se le atribuyen exclusivamente a la mujer debido a construcciones sociales "Esa construcción que, en síntesis, convierte a las hembras en sujetos femeninos, orientados centralmente hacia el trabajo de la reproducción y a los machos, en sujetos masculinos, centrados básicamente en el trabajo de la producción." (Carrasquer, 1998) feminizando de esa forma las labores de la esfera privada y  teniendo así que ejercer una "doble presencia" para las mujeres  y compatibilizar su trabajo reproductivo en el hogar con su vida laboral o productiva. Otra característica del trabajo reproductivo es la invisibilización del mismo por la sociedad y por las mismas mujeres que lo realizan y esto debido a que no se le considera trabajo productivo como mencionamos anteriormente (Carrasquer, 1998) [ver @pilarcarrasquerTrabajoReproductivo1998]

Esto suele ser relevante, ya que cabe plantearse si en parejas con doble ingreso la situación suele ser similar. Si bien, la carga de las labores domésticas en parejas de este tipo suele distribuirse mejor, delegando así parte de estas al hombre o a externalizar estas labores, la carga global de las mujeres sigue siendo mayor cuando el hombre dedica mayor tiempo al mercado laboral, aumentando así la brecha de género y afectando al desempeño laboral de la mujer, de tal manera que "los recursos relativos de las mujeres inciden muy poco en la brecha de género en el interior de los hogares, y son las actitudes y los valores masculinos los que tienen mayor impacto en la dedicación masculina al trabajo no remunerado, y por tanto en los procesos de desigualdad." (Dominguez. Muñiz, Rubilar, 2018) [@rubilardonosoTrabajoDomesticoCuidados2018]

De esta forma, la doble presencia que experimentan las mujeres en torno a trabajos remunerados y labores del hogar, generan una brecha de género que si bien, con la inserción de las mujeres al mercado laboral ha disminuido, no se ha mitigado por completo la desigualdad o la división del trabajo seuxal. generando así que el trabajo reproductivo tenga como efectos inmediatos "a pesar de no contar con una evaluación homologada y prestigiada, son: facilitar la disponibilidad laboral de los masculinos adultos del hogar-familia, en particular, y proporcionar bienestar cotidiano a los convivientes del núcleo familiar, en general" (Torns, 2008). @teresatornsTrabajoCuidadoCuestiones2008\]
